<?php

namespace BillingServ\LaravelWaf\Http\Responses;

final class ChallengePage
{
    public static function required(
        string $title,
        string $message,
        string $action,
        string $token,
        string $widget,
        string $script = '',
    ): string {
        $content = '<div class="challenge-top">'
            .'<span class="eyebrow">Security checkpoint</span>'
            .'<span class="page-code">WAF / 01</span>'
            .'</div>'
            .'<h1>'.self::escape($title).'</h1>'
            .'<p class="lede">'.self::escape($message).'</p>'
            .'<div class="challenge-panel">'
            .'<div class="panel-heading"><span class="panel-icon">'
            .self::shieldIcon('panel-shield')
            .'</span><div><strong>One quick step</strong><span>Confirm you are a real visitor.</span></div></div>'
            .'<form method="post" action="'.self::escape($action).'" autocomplete="off">'
            .'<input type="hidden" name="_waf_challenge" value="'.self::escape($token).'">'
            .'<div class="widget-shell">'.$widget.'</div>'
            .'<button type="submit">Continue securely <span aria-hidden="true">→</span></button>'
            .'</form>'
            .'<noscript><p class="no-script">JavaScript is required to complete this verification.</p></noscript>'
            .'</div>'
            .'<p class="privacy-note"><span class="status-dot"></span>Your connection is protected. This check usually takes a few seconds.</p>';

        return self::document($title, 'required', $content, $script);
    }

    public static function notice(string $title, string $message): string
    {
        $content = '<div class="challenge-top">'
            .'<span class="eyebrow">Security checkpoint</span>'
            .'<span class="page-code">WAF / 01</span>'
            .'</div>'
            .'<h1>'.self::escape($title).'</h1>'
            .'<p class="lede">'.self::escape($message).'</p>'
            .'<div class="challenge-panel notice-panel">'
            .'<div class="panel-heading"><span class="panel-icon">'
            .self::shieldIcon('panel-shield')
            .'</span><div><strong>Verification service</strong><span>Please try again shortly.</span></div></div>'
            .'</div>'
            .'<p class="privacy-note"><span class="status-dot"></span>This response was generated by the application firewall.</p>';

        return self::document($title, 'required', $content);
    }

    public static function failed(
        string $title = 'Verification failed',
        string $message = 'We could not confirm this request. Please try again.',
        ?string $retryUrl = null,
    ): string {
        $retryUrl = self::localUrl($retryUrl);
        $retry = $retryUrl === null
            ? '<p class="failure-help">Close this page and return to the site to try again.</p>'
            : '<a class="secondary-action" href="'.self::escape($retryUrl).'">Try again <span aria-hidden="true">↗</span></a>';

        $content = '<div class="challenge-top">'
            .'<span class="eyebrow">Verification error</span>'
            .'<span class="page-code">WAF / 02</span>'
            .'</div>'
            .'<h1>'.self::escape($title).'</h1>'
            .'<p class="lede">'.self::escape($message).'</p>'
            .'<div class="challenge-panel failure-panel">'
            .'<div class="failure-mark" aria-hidden="true">×</div>'
            .'<div><strong>We need a fresh confirmation</strong><span>The verification was missing, expired, or did not match.</span></div>'
            .$retry
            .'</div>'
            .'<p class="privacy-note"><span class="status-dot failure-dot"></span>No access was granted. Your request remains protected.</p>';

        return self::document($title, 'failed', $content);
    }

    private static function document(string $title, string $state, string $content, string $head = ''): string
    {
        return '<!doctype html><html lang="en"><head><meta charset="utf-8">'
            .'<meta name="viewport" content="width=device-width, initial-scale=1">'
            .'<meta name="color-scheme" content="light">'
            .'<title>'.self::escape($title).'</title>'
            .'<style>'.self::styles().'</style>'.$head.'</head><body class="state-'.$state.'">'
            .'<div class="page-shell"><div class="challenge-card">'
            .'<aside class="brand-rail">'
            .'<div><div class="brand">'.self::shieldIcon('brand-mark').'<span>Laravel WAF</span></div>'
            .'<div class="rail-rule"></div><p class="rail-kicker">Traffic protection<br>for this application</p></div>'
            .'<div class="rail-footer"><span class="rail-pulse"></span><span>Protected session</span></div>'
            .'</aside><main class="challenge-content">'.$content.'</main>'
            .'</div><p class="page-footer">Application firewall <span>•</span> Private, short-lived verification</p></div>'
            .'</body></html>';
    }

    private static function shieldIcon(string $class): string
    {
        return '<svg class="'.$class.'" viewBox="0 0 32 36" fill="none" aria-hidden="true">'
            .'<path d="M16 2.5 28 7v8.8c0 7.4-4.7 13.8-12 17.7C8.7 29.6 4 23.2 4 15.8V7l12-4.5Z" stroke="currentColor" stroke-width="2.2"/>'
            .'<path d="m10.5 17.2 3.7 3.7 7.5-8" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>'
            .'</svg>';
    }

    private static function localUrl(?string $url): ?string
    {
        if (!is_string($url) || $url === '' || strlen($url) > 2048 || str_contains($url, "\r") || str_contains($url, "\n")) {
            return null;
        }

        return str_starts_with($url, '/') && !str_starts_with($url, '//') ? $url : null;
    }

    private static function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }

    private static function styles(): string
    {
        return <<<'CSS'
:root {
    --night: #08252a;
    --night-soft: #10393c;
    --ink: #14282b;
    --muted: #667679;
    --line: #dce5df;
    --paper: #f7faf7;
    --surface: #ffffff;
    --mint: #d9f26d;
    --mint-deep: #315d4e;
    --coral: #e46e5c;
    --coral-soft: #fff1ed;
}

* { box-sizing: border-box; }

html, body { min-height: 100%; }

body {
    margin: 0;
    color: var(--ink);
    background: var(--night);
    font-family: "Avenir Next", "Segoe UI", sans-serif;
    -webkit-font-smoothing: antialiased;
}

body::before {
    position: fixed;
    inset: 0;
    pointer-events: none;
    content: "";
    opacity: .42;
    background:
        linear-gradient(115deg, transparent 0 42%, rgba(217,242,109,.08) 42.1% 42.25%, transparent 42.35%),
        radial-gradient(circle at 80% 15%, rgba(217,242,109,.17), transparent 30%),
        repeating-linear-gradient(90deg, rgba(255,255,255,.025) 0 1px, transparent 1px 72px);
}

.page-shell {
    position: relative;
    display: grid;
    align-content: center;
    width: min(100% - 32px, 920px);
    min-height: 100svh;
    margin: 0 auto;
    padding: 48px 0 28px;
}

.challenge-card {
    display: grid;
    grid-template-columns: minmax(210px, .72fr) minmax(0, 1.28fr);
    overflow: hidden;
    border: 1px solid rgba(255,255,255,.14);
    border-radius: 28px;
    background: var(--surface);
    box-shadow: 0 30px 80px rgba(0,0,0,.24), 0 4px 14px rgba(0,0,0,.1);
    animation: card-in .55s cubic-bezier(.2,.8,.2,1) both;
}

.brand-rail {
    display: flex;
    min-height: 530px;
    flex-direction: column;
    justify-content: space-between;
    padding: 34px 30px;
    color: #eef8e5;
    background:
        linear-gradient(155deg, rgba(217,242,109,.14), transparent 42%),
        var(--night-soft);
}

.brand {
    display: flex;
    align-items: center;
    gap: 11px;
    color: var(--mint);
    font-size: 15px;
    font-weight: 700;
    letter-spacing: -.02em;
}

.brand-mark { width: 25px; height: 29px; }

.rail-rule {
    width: 44px;
    height: 3px;
    margin: 78px 0 20px;
    border-radius: 99px;
    background: var(--mint);
}

.rail-kicker {
    margin: 0;
    color: rgba(238,248,229,.68);
    font-size: 13px;
    line-height: 1.6;
    letter-spacing: .02em;
}

.rail-footer, .privacy-note {
    display: flex;
    align-items: center;
    gap: 9px;
}

.rail-footer {
    color: rgba(238,248,229,.68);
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 10px;
    letter-spacing: .1em;
    text-transform: uppercase;
}

.rail-pulse, .status-dot {
    display: inline-block;
    width: 7px;
    height: 7px;
    flex: 0 0 auto;
    border-radius: 50%;
    background: var(--mint);
    box-shadow: 0 0 0 5px rgba(217,242,109,.11);
}

.challenge-content {
    padding: 52px clamp(28px, 6vw, 68px) 44px;
}

.challenge-top {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
}

.eyebrow, .page-code {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: .13em;
    text-transform: uppercase;
}

.eyebrow { color: var(--mint-deep); }
.page-code { color: #a3afb0; }

h1 {
    max-width: 510px;
    margin: 28px 0 14px;
    font-family: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
    font-size: clamp(40px, 5vw, 66px);
    font-weight: 500;
    letter-spacing: -.055em;
    line-height: .98;
}

.lede {
    max-width: 490px;
    margin: 0;
    color: var(--muted);
    font-size: 15px;
    line-height: 1.65;
}

.challenge-panel {
    margin-top: 34px;
    padding: 22px;
    border: 1px solid var(--line);
    border-radius: 18px;
    background: var(--paper);
}

.panel-heading {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 20px;
}

.panel-heading > div, .failure-panel > div:last-of-type {
    display: grid;
    gap: 3px;
}

.panel-heading strong, .failure-panel strong {
    font-size: 13px;
    letter-spacing: -.01em;
}

.panel-heading span:not(.panel-icon), .failure-panel span {
    color: var(--muted);
    font-size: 12px;
    line-height: 1.45;
}

.panel-icon {
    display: grid;
    width: 35px;
    height: 35px;
    place-items: center;
    border-radius: 11px;
    color: var(--mint-deep);
    background: #eaf6d3;
}

.panel-shield { width: 19px; height: 22px; }

.widget-shell {
    min-height: 74px;
    padding: 11px 13px;
    border: 1px solid var(--line);
    border-radius: 12px;
    background: var(--surface);
}

altcha-widget { display: block; }

button, .secondary-action {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 11px;
    min-height: 48px;
    border: 0;
    border-radius: 10px;
    font: inherit;
    font-size: 13px;
    font-weight: 700;
    letter-spacing: -.01em;
    text-decoration: none;
    transition: transform .2s ease, box-shadow .2s ease, background .2s ease;
}

button {
    width: 100%;
    margin-top: 14px;
    cursor: pointer;
    color: #173b35;
    background: var(--mint);
    box-shadow: 0 7px 14px rgba(49,93,78,.12);
}

button:hover, .secondary-action:hover { transform: translateY(-2px); box-shadow: 0 10px 19px rgba(49,93,78,.18); }
button:focus-visible, .secondary-action:focus-visible { outline: 3px solid rgba(228,110,92,.5); outline-offset: 3px; }

.no-script, .failure-help {
    margin: 14px 0 0;
    color: var(--muted);
    font-size: 12px;
    line-height: 1.5;
}

.privacy-note {
    margin: 20px 0 0;
    color: #889496;
    font-size: 11px;
    line-height: 1.5;
}

.failure-panel {
    display: grid;
    grid-template-columns: auto minmax(0, 1fr);
    align-items: center;
    gap: 12px;
    border-color: #f2d2cb;
    background: var(--coral-soft);
}

.failure-mark {
    display: grid;
    width: 35px;
    height: 35px;
    place-items: center;
    border-radius: 11px;
    color: #a54335;
    background: #ffdcd5;
    font-family: Georgia, serif;
    font-size: 25px;
    line-height: 1;
}

.secondary-action {
    grid-column: 1 / -1;
    margin-top: 7px;
    color: #fff;
    background: var(--coral);
}

.failure-dot { background: var(--coral); box-shadow: 0 0 0 5px rgba(228,110,92,.1); }

.page-footer {
    margin: 18px 0 0;
    color: rgba(238,248,229,.45);
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 10px;
    letter-spacing: .08em;
    text-align: center;
    text-transform: uppercase;
}

.page-footer span { margin: 0 7px; color: var(--mint); }

@keyframes card-in {
    from { opacity: 0; transform: translateY(14px); }
    to { opacity: 1; transform: translateY(0); }
}

@media (max-width: 680px) {
    .page-shell { width: min(100% - 20px, 540px); padding: 20px 0; }
    .challenge-card { grid-template-columns: 1fr; border-radius: 22px; }
    .brand-rail { min-height: 0; padding: 22px 24px; gap: 35px; }
    .rail-rule { margin: 32px 0 14px; }
    .challenge-content { padding: 34px 24px 30px; }
    h1 { margin-top: 24px; font-size: clamp(39px, 13vw, 58px); }
}

@media (prefers-reduced-motion: reduce) {
    *, *::before, *::after { animation-duration: .01ms !important; transition-duration: .01ms !important; }
}
CSS;
    }
}
